name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: "Build (${{ matrix.os }})"
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Set up JDK'
        uses: oracle-actions/setup-java@v1
      - name: 'Build with Bach'
        run: .bach/bin/bach build
      - name: 'Upload custom runtime image'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.os }}-${{ github.sha }}
          path: |
            .bach/out/main/image
